# Intent definition for Calendar skill
#
#  (c) A. Dominik, 2020
#
skill = "ADoSnipsDoNotListen"
developer = "andreasdominik"


[inventory]
intents = ["DoNotListen", "ListenAgain"]
slots = []


# define slots:
# Types: "Any", "ListOfValues", "Time", "Duration", "Currency", "Number", "Ordinal"
#


# define phrases for intent recognition:
# "exact", "regex", "partial", "ordered"
#

[DoNotListen]
do_not_listen_a = "exact: <<bitte|>> hör.? <<bitte|>> <<weg|nicht mehr zu>>"
do_not_listen_b = "exact: sei taub"
do_not_listen_c = "exact: sei still"

[ListenAgain]
listen_again = "exact: <<bitte|>> hör.? <<bitte|>> <<wieder zu|zu>>"
